flow:
  - script: "echo 'hello world'"
    envs:
      FLOW_WORKSPACE: "echo hello"
      FLOW_VERSION: "echo version"

    steps:
     - name: step1
       envs:
         FLOW_WORKSPACE: "echo step"
         FLOW_VERSION: "echo step version"
       isAllowFailure: true
       sleep 10
       script: "echo 1"

      
     - name: step2
       isAllowFailure: false
       sleep 5
       script: "echo 2"
